---
title: "Summarizing posteriors through tables in RMarkdown"
author: "Johannes Karreth"
date: "July 7, 2015"
output: pdf_document
---

## Simulate data and fit a model

```{r}
n.sim <- 100; set.seed(123)
x1 <- rnorm(n.sim, mean = 5, sd = 2)
x2 <- rbinom(n.sim, size = 1, prob = 0.3)
e <- rnorm(n.sim, mean = 0, sd = 1)
b1 <- 1.2
b2 <- -3.1
a <- 1.5
y <- a + b1 * x1 + b2 * x2 + e

sim.dat <- data.frame(y, x1, x2)

bayes.mod <- function()  {

for(i in 1:N){
y[i] ~ dnorm(mu[i], tau)
mu[i] <- alpha + beta1 * x1[i] + beta2 * x2[i]
}

alpha ~ dnorm(0, .01)
beta1 ~ dunif(-100, 100)
beta2 ~ dunif(-100, 100)
tau ~ dgamma(.01, .01)

}

sim.dat.jags  <- as.list(sim.dat)

sim.dat.jags$N  <- nrow(sim.dat)

bayes.mod.params <- c("alpha", "beta1", "beta2")


inits1 <- list("alpha" = 0, "beta1" = 0, "beta2" = 0) 
inits2 <- list("alpha" = 1, "beta1" = 1, "beta2" = 1)
inits3 <- list("alpha" = -1, "beta1" = -1, "beta2" = -1)
bayes.mod.inits <- list(inits1, inits2, inits3)

library(R2jags)
set.seed(123) 

bayes.mod.fit <- jags(data = sim.dat.jags, inits = bayes.mod.inits, 
  parameters.to.save = bayes.mod.params, n.chains = 3, n.iter = 9000, 
  n.burnin = 1000, 
  model.file = bayes.mod)
```

## Create a summary table

```{r}
devtools::source_url("https://raw.githubusercontent.com/jkarreth/JKmisc/master/mcmctab.R")
regtable <- mcmctab(as.mcmc(bayes.mod.fit))[-c(4), ]  # remove the fourth row
```

## Option 1: the pander package

```{r}
library(pander)
pander(regtable)
```

## Option 2: the knitr package

```{r}
library(knitr)
kable(regtable)
```